# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.2
notifications:
  email: false

services:
  - docker

script:
  - docker build -t juliareinforcementlearning/reinforcementlearningenvironments .